[server]
port = 8502
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = false
runOnSave = true

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8502
